name: Docker Testing

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t pyscioffice/vlab:latest .
      - run: docker images
